version: '3.7'

#ELK sử dụng version giống nhau

services:
  elasticsearch:
    image: elasticsearch:7.17.0
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:7.17.0
    ports:
      - '5601:5601'

  logstash:
    image: logstash:7.17.0
    ports:
      - '5044:5044' # binding port 5044 từ container ra máy host (post nhận dữ liệu từ filebeat)
    volumes:
      - type: bind
        source: ./logstash_pipeline/ # Thư mục cùng cấp với file docker-compose.yml chứa file config cho logstash
        
        # File logstash config sẽ được mount từ thư mục trên vào /usr/share/logstash/pipeline của container
        target: /usr/share/logstash/pipeline 
        read_only: true
        